apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngix-ingress
  annotations:
spec:
  rules:
    - http:
        paths:
        - path: /test
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80